/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.42.0.0
 *
 * Project: 'Project' 
 * Target:  'C8T6' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32f10x.h"

/* MDK-Packs::Data Exchange:JSON:cJSON@1.7.7 */
#define RTE_DataExchange_JSON_cJSON     /* cJSON */


#endif /* RTE_COMPONENTS_H */
